<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPINHYDW0D51" failures="5" tests="7" name="TestAPIOfAttendancesheet" time="33.72" errors="0" timestamp="2022-03-08T20:45:06 IST">
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestGetResponseOfAttendanceSheet" time="14.861"/>
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestPostResponseOfPunchIn" time="5.009">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet.TestPostResponseOfPunchIn(TestAPIOfAttendanceSheet.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestPostResponseOfPunchIn -->
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestPostResponseOfValidPunchOut" time="0.007">
    <failure type="java.lang.IllegalArgumentException" message="parameterValue cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:514)
at com.epam.TestAutomation.Project.API.Utilities.HttpsMethods.PatchPunchOut(HttpsMethods.java:109)
at com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet.TestPostResponseOfValidPunchOut(TestAPIOfAttendanceSheet.java:89)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestPostResponseOfValidPunchOut -->
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestPostResponseOfPunchInOverlapping" time="3.63"/>
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestPatchtResponsePunchOutAgainAfterPunchOut" time="0.001">
    <failure type="java.lang.IllegalArgumentException" message="parameterValue cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: parameterValue cannot be null
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.RequestSpecificationImpl.pathParam(RequestSpecificationImpl.groovy:514)
at com.epam.TestAutomation.Project.API.Utilities.HttpsMethods.PatchPunchOut(HttpsMethods.java:126)
at com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet.TestPatchtResponsePunchOutAgainAfterPunchOut(TestAPIOfAttendanceSheet.java:123)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestPatchtResponsePunchOutAgainAfterPunchOut -->
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestPatchtResponsePunchOutBeforePunchIn" time="2.492">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;201&amp;gt; but was &amp;lt;403&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <201> but was <403>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:492)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:655)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:125)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:133)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1262)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy:142)
at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
at com.epam.TestAutomation.Project.API.Utilities.HttpsMethods.PostPunchIn(HttpsMethods.java:99)
at com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet.TestPatchtResponsePunchOutBeforePunchIn(TestAPIOfAttendanceSheet.java:143)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- TestPatchtResponsePunchOutBeforePunchIn -->
  <testcase classname="com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet" name="TestTotalHoursAggregation" time="7.242">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 1 out of bounds for length 1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.epam.TestAutomation.Project.API.Utilities.ParseTime.convertIntoMinutes(ParseTime.java:10)
at com.epam.TestAutomation.Project.APITesting.Tests.TestAPIOfAttendanceSheet.TestTotalHoursAggregation(TestAPIOfAttendanceSheet.java:174)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestTotalHoursAggregation -->
</testsuite> <!-- TestAPIOfAttendancesheet -->
